### PR TITLE
beter versioning

### PR DESCRIPTION
**Pull request by calvinmetcalf**
alternative way to do #210

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
the downside is we have a dependency, we could also statically generate lib/version-browser durring the publish step

**Comment by calvinmetcalf** [comment]
ok this one instead has a placeholder file which gets overwritten when we build things before publishing

**Comment by atlefren** [comment]
This approach sounds much better than requireing the end-user to install packages and tweak configs!

**Comment by calvinmetcalf** [comment]
@atlefren fyi if you don't want to install configs/packages you should probably avoid webpack, it's designed with app builders installing global transforms in mind.  But this particular fix should also help browserify users as well by making their build smaller.

**Comment by calvinmetcalf** [comment]
@ahocevar I actually did it without the extra dep so even better

**Comment by ahocevar** [comment]
👍 thanks @calvinmetcalf.

**Pull request merged**
