### PR TITLE
Re-add units to srs definition

### LINKED ISSUE #142: Units definition issue with 2.3.5
With version 2.3.5, the `units` value doesn't seem to be correctly handled:
```javascript

proj4.defs('ESRI:53009', '+proj=moll +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs');

var proj = proj4.defs('ESRI:53009');
proj.units == undefined;
```

Related to https://github.com/openlayers/ol3/pull/3523

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes a regression introduced with 5c64b03362dc9c3113ee241c530c41d67b3a29b1.

Fixes #142.

### CODE REVIEW

**Comment by fredj** [comment]
Thanks @ahocevar, this change fixes my ol3 issue

**Comment by ahocevar** [comment]
@calvinmetcalf Since this fixes a regression, I took the liberty to merge based on user review. Feel free to revert if you don't agree.

**Comment by calvinmetcalf** [comment]
nope it looks good

**Comment by ahocevar** [comment]
Published v2.3.6 with this fix.

**Pull request merged**
