### PR TITLE
Fix transformations

### PR DESCRIPTION
**Pull request by KaloNK**
geocentricToWgs84 and geocentricFromWgs84 replaced with a single function

### CODE REVIEW

**Review by ahocevar — CHANGES_REQUESTED** [review]
Thanks for trying to fix this, @KaloNK. 304 tests are failing with this change. But before you spend more time on this, did you follow my advice in #412 to check if you were using the same transform in proj4 as in your reference example?

**Comment by KaloNK** [comment]
I am working with EPSG:28405 (  https://epsg.io/28405 ) and using exactly the string provided for poj4js on that page:
`proj4.defs("EPSG:28405","+proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=5500000 +y_0=0 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,-0.35,-0.79,-0.22 +units=m +no_defs +type=crs");`

Without my change the results are shifted 5 to 20 meters from the same results at epsg.io - https://epsg.io/transform#s_srs=4326&t_srs=28405&x=27.9217725&y=43.1873279

After the change, the results are identical.

**Comment by ahocevar** [comment]
So far so good. Now in order to be able to accept this pull request, we need to know whether the 304 failing tests make wrong assumptions (some results are 200 m off after your change), or how to proceed.

**Comment by KaloNK** [comment]
To manually check (on epsg.io) all 304 will take a lot of time, but maybe just those that are too different.
If 10 of 10 results are confirmed on epsg.io it should be enough i think.

**Comment by ahocevar** [comment]
I can confirm your findings in the two cases you provide, but I find it hard to believe we've been doing the Helmert transformation wrong since forever.

i checked some of the tests, and I was able to confirm that our assumptions for EPSG:31370 were indeed wrong. But all the others I checked were correct before your change, and are failing with your change.

To make more sense out of your change, would you be able to provide a citation for your code or the algorithm that you used?

**Comment by KaloNK** [comment]
just followed https://en.wikipedia.org/wiki/Helmert_transformation (Application):
"for each single parameter of the coordinate"  and "For the reverse transformation, each element is multiplied by −1."

**Comment by ahocevar** [comment]
Your're using the wrong sign for the matrix parameters when transforming to WGS84, and not applying the scale for the input points when transforming back. Like I wrote in #412, there is no need for this pull request, because nothing is broken.

**Pull request closed without merging**
