### PR TITLE
fload mgrs dep

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
merged though @ahocevar can you publish, I'm going to be honest that I don't remember how

**Comment by ahocevar** [comment]
I'll try tomorrow morning @calvinmetcalf, I'm too tired now.

**Comment by ahocevar** [comment]
@calvinmetcalf Published, using the instructions in PUBLISHING.md. However, I think that the dist directory of mgrs was not properly updated when you published mgrs 0.0.2. So I added a publish.sh script an PUBLISHING.md instructions to mgrs as well, in case you want to publish 0.0.3 there.

**Comment by ahocevar** [comment]
@calvinmetcalf I went ahead and published mgrs 0.0.3, using the new publish.sh script and PUBLISHING.md instructions there.

**Comment by calvinmetcalf** [comment]
thanks!

**Pull request merged**
