### PR TITLE
Add WGS84 / UTM zones as predefined CRS

### PR DESCRIPTION
**Pull request by ahocevar**
For convenience.

### CODE REVIEW

**Comment by christophfriedrich** [comment]
The readme doesn't reflect the code correctly: The loop adds 32600 to 32660 and 32700 to 32760, but the text only lists from 32x0**1**, and both bullet points are identical where it should be x=6 in the first and x=7 in the second point.

**Comment by ahocevar** [comment]
Thanks @christophfriedrich, that's fixed already in the latest release.

**Comment by christophfriedrich** [comment]
Oh ok, I didn't see the later commit. That fixes the identical lines. The codes ending in `00` are still missing though (the loop starts at zero, so adds 32600 and 32700, but they are not mentioned in the text).

**Comment by ahocevar** [comment]
@christophfriedrich Good point, that's a mistake in the code then. The UTM zones start at 32601 and 32701. I'll create a follow-up pull request.

**Pull request merged**
