### PR TITLE
Fixed calculation for angular distance c, see Snyder 1987, formula 21-15

### PR DESCRIPTION
**Pull request by swalterfub**
Described in Issue #193. For the correct formula, see 21-15 on page 159 of Synder: https://pubs.usgs.gov/pp/1395/report.pdf

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
a test would be great so we could avoid regressing this, otherwise this looks great

**Comment by swalterfub** [comment]
Test is added. Is it what you meant? The coordinates in the test are retrieved by the proj command line utility

**Comment by calvinmetcalf** [comment]
yes, will take a look

**Comment by malaretv** [comment]
Indeed this fixes the issues i was having in #193. Thanks @swalterfub !!

Is there anything keeping this from being merged in I could help out with?

**Pull request merged**
